### ISSUE TITLE
"ergonomic" attachment support

### ISSUE THREAD

**Issue by benjaminweb** [jonhoo/rust-imap#157]
Does rust-imap support message.attachments[i] notation or something similar to work with the attachments of a mail? I could not find anything apart from bodystructure and issue #116.

https://github.com/martinrusev/imbox (Python lib) seems to have an ergonomic user interface.

**Comment by jonhoo** [comment]
@benjaminweb The crate does as little parsing as it can, limiting itself just to the IMAP standard itself. You'd generally want a higher-level library like `mailparse` to parse the _contents_ of emails. Now, you may need `BODYSTRUCTURE` to do so, and there I'm mostly just waiting on tests from @avitex in https://github.com/jonhoo/rust-imap/pull/134, so that'd be the issue to watch :)
