### ISSUE TITLE
imap-proto is stuck to ^0.10.0 on crates.io

### ISSUE THREAD

**Issue by Rulliam** [jonhoo/rust-imap#182]
Hi,

I think there is a bug in how you deploy this crate on crates.io , the dependency imap-proto is stuck to ^0.10.0 (so 0.10.2) version on crates.io :
https://crates.io/crates/imap/2.4.1/dependencies

Could you patch this so we can profite of the last version of imap-proto ? which is 0.14.0 in your Cargo.toml

**Comment by Rulliam** [comment]
I found that because I have a bug in some imap servers which is fixed with imap-proto 0.12.1

**Comment by jonhoo** [comment]
That's not a bug — 0.14 is a different major version than 0.10, so changing from one to another would be a breaking change to `imap`, and would thus require a major version bump. One is coming down the line (see `3.0.0-alpha`), but I can't upgrade 2.x since imap-proto is in the public interface of imap :)

**Comment by Rulliam** [comment]
Ok thank you ! and sorry for this issue^^

**Comment by jonhoo** [comment]
No worries at all!
